server:
  port: 9999
spring:
  application:
    name: conn
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/conn
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conn
    username: postgres
    password: postgres
#  kafka:
#    producer:
#      bootstrap-servers: 127.0.0.1:9092
#      transaction-id-prefix: kafkaTx-
#      retries: 3
#      acks: all
#      batch-size: 16384
#      buffer-memory: 1024000
#      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      bootstrap-servers: 127.0.0.1:9092
#      group-id: default-group
#      auto-offset-reset: latest
#      enable-auto-commit: false
#      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
#        max-poll-records: 3
#    listener:
#      concurrency: 4
#      ack-mode: manual_immediate
#      missing-topics-fatal: false
#      poll-timeout: 600000

