server:
  port: 9999
spring:
  application:
    name: conn
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/conn
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conn
    username: postgres
    password: postgres

